### ISSUE TITLE
Installation of numpy via setuptools

### ISSUE THREAD

**Issue by matkrak** [DataMedSci/beprof#10]
1. Find a way to install both numpy and scipy using setuptools (installation process should succeed and this should not depend on OS system)
2. Find out which version of both numpy and scipy is required for beprof to work properly and make proper changes in setup.py file

**Comment by grzanka** [comment]
I suspect that installation of numpy and scipy under Windows, using setuptools will require compiler (Visual Studio). This is why preferred installation method for Windows is to download pre-compiled numpy and scipy. Precompiled artifacts are available as .exe files on the Internet and I think it's impossible to force pip/setuptools to use these .exe files instead of compiling from sources.

This task requires deeper studies how setuptools/pip works and how numpy/scipy is distributed.

**Comment by antnieszka** [comment]
I think this is now Windows specific issue. @grzanka Should I label and rename it?

**Comment by grzanka** [comment]
Yes, rename it. Also check how was it done for appveyor config.

First get rid of scipy: #68 

I would say now that this task has following scope:
1. Get clean windows OS
2. Install python (2 and/or 3) as most users would do it (google "python" -> download -> install)
3. Try to install beprof using pip (ie. latests from GIT). Numpy will be missing, see how installation will fail.
4. Install numpy as most users would do it (google "numpy" -> download -> install). Most users probably won't choose anaconda.
5. Try to instal beprof again using pip.

Make sure that what we have in the repo will work with typical way users install Python & numpy on windows.

**Comment by antnieszka** [comment]
On clean windows 7:
1. Get Python:
   ![g1](https://cloud.githubusercontent.com/assets/5757700/20099282/faf245d2-a5b7-11e6-96db-239e32a281af.PNG)
   ![ins0](https://cloud.githubusercontent.com/assets/5757700/20099285/ff18afe8-a5b7-11e6-950a-ff7352cdc8cb.PNG)
   ![ins1](https://cloud.githubusercontent.com/assets/5757700/20099296/09bb24da-a5b8-11e6-93bc-e420079217e0.PNG)
   (Note: 'add to PATH' not selected - default setting)
2. Pip?
   ![con0](https://cloud.githubusercontent.com/assets/5757700/20099388/88296a66-a5b8-11e6-9843-cb849e1a8d77.PNG)
   It seems it's in local files... ☹️
   ![def_loc0](https://cloud.githubusercontent.com/assets/5757700/20099471/de68e55a-a5b8-11e6-9df0-57578fea6d66.PNG)
   (I'll assume user has repo link to use pip here)
   ![err](https://cloud.githubusercontent.com/assets/5757700/20099522/33b4391a-a5b9-11e6-905c-b376e6e39609.PNG)
   Soooooo Git is needed, I wrote about it here: #97 
3. Let's do _Google-install_ trick once more and get Git:
   I'll omit screenshots from this step - just assume user googles git, downloads _Git - Download for Windows_ and installs it.
4. Here goes another problem - git is not added to PATH, we need to rerun cmd.exe
5. cd to Python dir and use pip install git...
   ![test](https://cloud.githubusercontent.com/assets/5757700/20099782/a7efb38a-a5ba-11e6-97ed-5883ce7bcdca.PNG)
   Now better 😃 
   And numpy is also auto-downloaded, so this is it.

**Comment by antnieszka** [comment]
@grzanka I would add some info about git to our README, it's also missing on raw linux distros #97 - and this should do.

**Comment by grzanka** [comment]
Good idea. There is also another thing. If user would install python and click "Add python 3.5 to PATH" then the problem would disappear. We could also suggest to use Anaconda.

**Comment by antnieszka** [comment]
But git would still be required :/

**Comment by antnieszka** [comment]
I mean - Anaconda does not contain git, does it?

**Comment by grzanka** [comment]
No, it doesn't. But it can be solved this way:
- regular (ignorant) Windows user will work with anaconda + beprof released via pypi (https://pypi.python.org/pypi/beprof), then only `pip install beprof` is needed
- advanced Windows user who wants to have really latest fresh version directly from github will know how to install git.

Its usage should be similar to usage of numpy. Do you need git to get numpy ?

**Comment by antnieszka** [comment]
No, we don't. I just assumed that we don't have pypi beprof, because it does not work yet.
