### ISSUE TITLE
Travis py3.2 fails because of versioneer/virtualenv

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#103]
From latest PR build: https://travis-ci.org/DataMedSci/beprof/jobs/180835593
```
[...]

+[[ py32 == py32 ]]
+pip install git+https://github.com/grzanka/python-versioneer.git@support_python32
Collecting git+https://github.com/grzanka/python-versioneer.git@support_python32
  Cloning https://github.com/grzanka/python-versioneer.git (to support_python32) to /tmp/pip-095pz8-build
Exception:
Traceback (most recent call last):

[...]

  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pkg_resources/__init__.py", line 78, in <module>
    raise RuntimeError("Python 3.3 or later is required")
RuntimeError: Python 3.3 or later is required
/home/travis/build.sh: line 151:  3977 Terminated              travis_jigger $! $timeout $cmd
The command "if [[ $TRAVIS_OS_NAME == "linux" ]]; then travis_wait bash ./.travis/install_linux.sh ; fi" failed and exited with 2 during .

[...]
```

**Comment by grzanka** [comment]
There is no need to use dedicated version of versioneer package here:
https://github.com/DataMedSci/beprof/blob/master/.travis/install_linux.sh

```
if [[ $TOXENV == py32 ]];
then
  pip install git+https://github.com/grzanka/python-versioneer.git@support_python32
else
  pip install --upgrade versioneer
fi
```

Check pymchelper project:
https://github.com/DataMedSci/pymchelper/commits/master/.travis/install_linux.sh
https://github.com/DataMedSci/pymchelper/commit/9a2c595b3ebd602089cbdd75348b18a5d8bb385b#diff-010b8e24eee2fef58bbfe7da4889842f
https://github.com/DataMedSci/pymchelper/blob/master/tests/requirements-test.txt

Move versioneer to tests/requirements-test.txt file and use single version for all python versions, it should work now.

**Comment by ant6** [comment]
@grzanka please review :)
