### ISSUE TITLE
Investigate print(Profile object) error

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#115]
This small snippet of code
```py
import numpy as np
import time
from profile import Profile

a = np.ones(1000000)
b = np.ones(1000000)
c = np.stack((a, b), axis=0)
p = Profile([c])
print(p)
```
caused this:
```py
(beprof3) ~/PycharmProjects/beprof@feature/19-unit-testing✗✗✗✗✗✗ ant6% ➜ export PYTHONPATH=$PYTHONPATH:beprof/                  
(beprof3) ~/PycharmProjects/beprof@feature/19-unit-testing✗✗✗✗✗✗ ant6% ➜ python beprof/perf.py 
Traceback (most recent call last):
  File "beprof/perf.py", line 13, in <module>
    print(p)
  File "/home/ant6/PycharmProjects/beprof/beprof/profile.py", line 153, in __str__
    ret = curve.Curve.__str__(self)
  File "/home/ant6/PycharmProjects/beprof/beprof/curve.py", line 241, in __str__
    "\nMetadata : " + str(self.metadata)
TypeError: non-empty format string passed to object.__format__

```
Same thing happens when I use only Curve, not Profile in snippet above.

**Comment by grzanka** [comment]
Questions:
 - how `__str__` works when there is no metadata ?
 - what is the dimensionality of the parameter you pass to Profile constructor (`[c]`) ? Why do you pass `[c]` and not c ? What is expected shape (numpy shape) of objects passed to Profile ?

**Comment by antnieszka** [comment]
I investigated this further and got some results/thoughts. First of all:
![screenshot from 2016-12-09 20-22-28](https://cloud.githubusercontent.com/assets/5757700/21061622/67e349e0-be4d-11e6-8039-ac59361ef9a3.png)
and when I use numpy.min() - we're working with ndarray after all:
![screenshot from 2016-12-09 20-24-41](https://cloud.githubusercontent.com/assets/5757700/21061674/9d8b084e-be4d-11e6-8795-ad0e9d7477a0.png)
So indeed `.format()` may have issues, because we want to format floats in string, and not passing such to format function. Maybe for now we shoud:
1. use numpy.min()/max()
2. cast it to float()
![screenshot from 2016-12-09 20-27-29](https://cloud.githubusercontent.com/assets/5757700/21061750/ef494efc-be4d-11e6-91d9-08cb420d7b5a.png)

So my proposition is change `curve.__str__()` from this:
```py
    def __str__(self):
        logger.info('Running {0}.__str__'.format(self.__class__))
        ret = "shape: {}".format(self.shape) + \
              "\nX : [{:4.3f},{:4.3f}]".format(min(self.x), max(self.x)) + \
              "\nY : [{:4.6f},{:4.6f}]".format(min(self.y), max(self.y)) + \
              "\nMetadata : " + str(self.metadata)
        return ret
```
to this:
```py
    def __str__(self):
        logger.info('Running {0}.__str__'.format(self.__class__))
        ret = "shape: {}".format(self.shape) + \
              "\nX : [{:4.3f},{:4.3f}]".format(float(self.x.min()), float(self.x.max())) + \
              "\nY : [{:4.6f},{:4.6f}]".format(float(self.y.min()), float(self.y.max())) + \
              "\nMetadata : " + str(self.metadata)
        return ret
```
It works. Nothing is wrong with 'metadata' part, it's just misleading error message ☹️

**Comment by grzanka** [comment]
I agree with your proposition, it makes sense
