### ISSUE TITLE
Release 0.1.0 to PyPi

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#125]

**Comment by antnieszka** [comment]
@grzanka can you take care of that?

**Comment by grzanka** [comment]
@ant6 yes, I'll take care. It should be 0.1.0 not 0.1.1

**Comment by antnieszka** [comment]
@grzanka Great :) I'll change the names then.

**Comment by grzanka** [comment]
Its funny, I've got here: https://travis-ci.org/DataMedSci/beprof/jobs/184028591 an error:
```
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 5 of 5
It appears you're uploading to pypi.python.org (or testpypi) you've recieved a 500 error response. PyPI is being phased out for pypi.org. Try using https://upload.pypi.org/legacy/ (or https://test.pypi.org/legacy/) to upload your packages instead. These are the default URLs for Twine now.
HTTPError: 500 Server Error: Internal Server Error for url: https://pypi.python.org/pypi
```

Later I've deleted my initial attempt of making 0.1.0 release.

I wonder if it means that https://pypi.python.org/pypi/beprof (or https://pypi.python.org/ in general)  is being replaced with https://pypi.org/search/?q=beprof (or https://pypi.org in general)

**Comment by antnieszka** [comment]
Maybe that's because of heavy load? I can see some similar problems with 500 and in most cases 'it just worked after some time'... :octocat:

**Comment by antnieszka** [comment]
Even Wercker throws random 500's ☹️

**Comment by grzanka** [comment]
I don't think so, Pypa team is cooking new portal/service for distributing pip packages.
See https://pypi.org/ and https://warehouse.readthedocs.io/:

> Warehouse is a new code base that implements a Python package repository. It is being actively developed and the plan is that it will eventually power PyPI and replace an older code base that is currently powering PyPI. You can see Warehouse in production at https://pypi.org/


They already have new server address in instructions. See https://packaging.python.org/distributing/#create-an-account

```
[distutils]
index-servers=pypi

[pypi]
repository = https://upload.pypi.org/legacy/
username = <username>
password = <password>
```

I've updated accordingly: https://github.com/DataMedSci/beprof/pull/126/commits/8855788f489f2532ace4a7b95df555916ae21332

**Comment by grzanka** [comment]
Another attempt: https://travis-ci.org/DataMedSci/beprof/builds/184220859

**Comment by antnieszka** [comment]
@grzanka https://pypi.python.org/pypi/beprof/ went well, closing.
