### ISSUE TITLE
Add logging package

### ISSUE THREAD

**Issue by matkrak** [DataMedSci/beprof#14]
Provide logging package so that user know if some of the functions which were used don't work properly. 
Example of function that needs logging might be change_domain() method of Curve class.

**Comment by matkrak** [comment]
Since I have never wrote this kind of thing before, I will have to study existing solutions first. I understand, that I should use `logging` package: https://docs.python.org/3.5/library/logging.html.
If so, shouldn't take more then 2 hours.

**Comment by matkrak** [comment]
What logging messages should I provide?
For sure logging.errors when functions like change domain couldn't be executed properly.
If I skim the code I could put warnings in a couple of places as well.
The only one exception for now would be probably in subtract function (no creating new object but not possible to subtract with given domains)
Should I provide logging info and debug to a file, and if so, what should I put in this logs?
Also I understand, that this error logs should be printed to the console, or both to the console and to the file. Am I right?

**Comment by grzanka** [comment]
At the beginning assume that logs are printed only to the console. Set logging level such that only warnings of higher errors show up.

Add debug logging where necessary (i.e. object creation).
User error reporting wisely, together with exception catching/rising.

We also assume that the objects we are dealing with have proper shape - here might be the place to do some checks also.
