### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#19]
Consider first which framework to use:
- unittests
- nose

**Comment by matkrak** [comment]
Seems not very complicated. Need to read the documentation and then write some code. Should be 2-3 hours of work

**Comment by matkrak** [comment]
Both looks OK. Lets say I want to use unittests. Should I rewrite current docstring tests as unittests?

**Comment by grzanka** [comment]
doctests in docstring should stay as descriptive examples. They are more like documentation than like tests.
unittests should be more precise and broad. They should also cover all corner-cases.

**Comment by antnieszka** [comment]
@grzanka I remember we agreed on using pytest but where should I put tests? Separate directory alongside `beprof/` or in `beprof/tests/`? http://pytest.org/latest/goodpractices.html#choosing-a-test-layout-import-rules

**Comment by grzanka** [comment]
I prefer separate directory alongside `bprof`. In this way we could (in the future) make separate directories for:
- `test/unit_test`
- `test/integration_test`

**Comment by antnieszka** [comment]
Ok, with that in mind I'll create `test/unit_test` and put unit tests there. Another question - test_beprof.py was meant to do something particular or just to check configuration and I can remove it?

**Comment by grzanka** [comment]
Good. You can remove `test_beprof.py` - its trash.

**Comment by antnieszka** [comment]
@grzanka Maybe we could move this task to v0.1.1, close old milestone (0.1.0) and start working on new one?

**Comment by grzanka** [comment]
Sure

**Comment by antnieszka** [comment]
Resolved in #110
