### ISSUE TITLE
Provide decent __str__ methods for all classes

### ISSUE THREAD

**Issue by matkrak** [DataMedSci/beprof#24]
Instead of using `print('X: ', ex.x)` all the time write a good **str** representation of objects. Three main classes are
I) Curve
II) Profile
III) LateralProfile

The questions are:
1) What info should be provided for each of the classes
2) Having in mind that III is a subclass of II which is subclass of I, should **str** method for the last two use **str** method from the class 'above' ?

**Comment by grzanka** [comment]
See issue #25

**Comment by antnieszka** [comment]
Curve and Profile both have good enough `__str__()` methods, improved in #110.
