### ISSUE TITLE
Implement rebinning methods

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#4]
Implement rebinning of curve, assuming set of new X coordinates is given.
Rebinning is possible only if set of new coordinates is incluced in domain of original curve [Xmin, Xmax].

Provide also a way to do a rebinning with regular grid on X with given step, fixed on given value.
Examples: 
- regular grid with step 0.1 fixed on zero is: -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, ....
- regular grid with step 0.5 fixed on 0.1 is: -0.9, -0.4, 0.1, 0.6, 1.1, ...

Figure out how to calculate effectively such regular grid knowing:
- domain of original curve (Xmin, Xmax), i.e. (-2.01, 3.01)
- step (i.e. 0.1)
- fixation point (i.e. 0)

**Comment by grzanka** [comment]
Rebinning should make new object in memory as it is very probable that it will change number of points in the curve.

**Comment by matkrak** [comment]
If the base curve has a domain [x1, x2] how do you understand regular grid with fixed step = e and fixation point = fp?
1) It should be only possible if fp is in [x1, x2]
2) There should be fp, and there should be points 
     [.....fp-2_e, fp-e, fp, fp+e, fp+2_e.........] 
     but how many of them? 2 example solutions:
        I) fp should always be the centre of the section, and the number of points is determined 
           by value min(fp-x1, x2-fp)
        II) New domain should have as many points as it can what generally doesn't make fp the centre 
            of the section.
i.e. [x1, x2] = [0, 5], e = 1, fp = 1
I) new domain is:    [0, 1, 2]
II) new domain is:   [0, 1, 2, 3, 4 , 5]

**Comment by grzanka** [comment]
This will be indirect, "political" answer.

Fixation point might be outside domain. 

Imagine you have several curves with domains:
- c1 -> { -3.611, -1.22, -0.22, 0.3, 1.0 }
- c2 -> { -7.1, -4.3, -3.0, -2.2 }
  -  c3 -> { 5.1, 5.2, 5.33, 5.49999 }
    I want "regularize" all of them in one loop with step 0.1, centered around zero, i.e. like this:

`tmp = [ c.rebinnned( step=0.1, fp=0) for c in (c1,c2,c3 ]`

It cannot be done with fixation point always in the domain.

Speaking in language of mathematics.
old_domain = {  x_i : i = 0...n , x_i > x_j for i > i }
grid = { n \* step + fp : step > 0, fp \in R, N \in Z}
new_domain = { x in \grid : x >= x_0 and x <= x_n }

Be carefull with numpy and numerical precision of >= operator !
