### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#40]
Maybe we should use code some coverage tool from the beginning? E.g: https://codeclimate.com/github/ant6/beprof
This tool generates some badges:
[![Code Climate](https://codeclimate.com/github/ant6/beprof/badges/gpa.svg)](https://codeclimate.com/github/ant6/beprof)
[![Test Coverage](https://codeclimate.com/github/ant6/beprof/badges/coverage.svg)](https://codeclimate.com/github/ant6/beprof/coverage)
[![Issue Count](https://codeclimate.com/github/ant6/beprof/badges/issue_count.svg)](https://codeclimate.com/github/ant6/beprof)

**Comment by grzanka** [comment]
Sure, I'll register add this package to codeclimate.

**Comment by grzanka** [comment]
I'll add badges with next update coming from cookiecutter

**Comment by antnieszka** [comment]
Closed in: a2c7e9962c5caada29afbc7d7ae0db5419766573
