### ISSUE TITLE
Links need to be fixed after migration to organization

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#48]

**Comment by grzanka** [comment]
Requires.io is paid when repo is in the organization (https://requires.io/plans/). Please remove this badge.

**Comment by grzanka** [comment]
For appveyor, use this one: https://ci.appveyor.com/api/projects/status/nqcdxcm8pjs9j8pg?svg=true
with following link: https://ci.appveyor.com/project/grzanka/beprof-j6tr6

**Comment by grzanka** [comment]
Codeclimate is rendering now, I've added repo

**Comment by antnieszka** [comment]
Done in 39138b2c1870f2e38155edc5c85f9e59853417ae: [new README](https://github.com/ant6/beprof/blob/39138b2c1870f2e38155edc5c85f9e59853417ae/README.rst)

**Comment by grzanka** [comment]
I had to change appveyor link, now its added as github repo (was simple git repo).
New link is: https://ci.appveyor.com/api/projects/status/y06jw47ir3gvvgta?svg=true and points to: https://ci.appveyor.com/project/grzanka/beprof

Can you change it ?

**Comment by antnieszka** [comment]
Consider it done
