### ISSUE TITLE
Metadata handling

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#5]
To each curve one can assing some metadata. For example:
- name of file from which data was taken
- range
- date of measurement
- title to be set on the plot etc...
  It might be that there are no metadata, only one item or many.

Assuming that our classes derive from np.array, make sure that when making new objects (see i.e. #4 ) metadata is also copied to new object.

**Comment by matkrak** [comment]
1) Should metadata be field of Curve or Profile class. 
2) One should be able to give any metadata or there should be particular types (like these you mentioned: range, date etc.). 
3) How do you want this metadata to be entered. Should it be separate class for them and Curve should consist an instance of this class or you prefer another solution?

**Comment by grzanka** [comment]
Ad1) it should be field of Curve class. But they should be inherited by all subclasses and subsubclasses. I should be able to create object of i.e. DistalProfile class and add a "range" metadata with value 0.9.

Ad2) Any metadata.

Ad3) The simplest solution is to keep a dictionary with metadata.
It could work as follows (some methods are not implemented, I know):

```
p = Profile([....])
p.data['range'] = 9 # adding metadata
x = p.data['range'] + 3 # using metadata
q = p.interpolate(step=0.1) # creating new object
y = q.data['range'] + 5 # still can use metadata
r = DepthProfile(q) # subclassing
z = r.data['range'] + 7 # still can use metadata
```

It would be better to have it in following way:

```
p = Profile([....])
p.addField('range')
p.range = 0.9
```

but this requires more effort I think.

**Comment by matkrak** [comment]
I am going to follow the first solution for now.
Does it mean `__new__` of Curve should look more less like this:

```
def __new__(cls, input_array, **meta):
    cls.data = np.asarray(input_array)
    if meta is None:
        cls.metadata = {}
    else:
    cls.metadata = meta
return cls
```

Don't know if the piece of code above is going to work,
it is just a scratch of an idea. Should I follow it?

**Comment by grzanka** [comment]
As a scratch of idea looks OK, but first you need to understand how subclassing numpy array works:
http://docs.scipy.org/doc/numpy-1.10.1/user/basics.subclassing.html (this includes deeper knowledge of numpy: views etc).

Then make some tests with subclassing and creating a new objects.
Write some method which changes number of points in the curve and see if it maintaines metadata.
