### ISSUE TITLE
Investigate requiresio

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#51]
It looks that for public repo in organizations requiresio is for free - check this out:
https://requires.io/github/DataMedSci/beprof/requirements/?branch=master

It it works correctly, badge has to be added again

**Comment by antnieszka** [comment]
Looks good. I'll add it and commit straight to master.

**Comment by grzanka** [comment]
OK

**Comment by antnieszka** [comment]
Done in d931d10ab31bc742c816ad68dcb96033027532fe
