### ISSUE TITLE
Register beprof in main pypi repository

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#54]
Should be done once builds are passing and minimum functionality is available

**Comment by antnieszka** [comment]
How about setting a milestone and adding some issues/tasks to make it more visible?

**Comment by grzanka** [comment]
Good idea. I think we could follow semantic versioning and call first (beta) version 0.1.0.
Can you create milestone and assing the task which you think that should go there ?

**Comment by antnieszka** [comment]
Ok, I'll try.

**Comment by antnieszka** [comment]
@grzanka I think I'm done.

**Comment by grzanka** [comment]
Looks reasonable. I will add one issue soon

**Comment by grzanka** [comment]
Package added to pypi:
https://pypi.python.org/pypi/beprof/

When tests are done I'll make a 0.1.0 release which will be automatically uploaded to pypi.
