### ISSUE TITLE
Think of better names for github labels

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#64]
See i.e. http://programmers.stackexchange.com/questions/129714/how-to-manage-github-issues-for-priority-etc

**Comment by antnieszka** [comment]
Looks good, but do we need so many labels for a comparably small project as this one?

**Comment by grzanka** [comment]
I would prefer a minimal set with:
- type of issue (bug, feature, doc)
- importance of issue

This require more studies

**Comment by grzanka** [comment]
My proposition:
- "Type: bug" / red   (description: some functionality is broken)
- "Type: feature" / green  (description: new functionality is added)
- "Type: question" / yellow (description: discussion, decision making)
- "Importance: major" / blue (description: critical bug, important features)
- "Importance: minor" / ??? (description: can wait)

**Comment by grzanka** [comment]
We can add more labels later

**Comment by antnieszka** [comment]
Maybe:
- Major - dark blue
- Minor - light blue

I agree with the rest of colors/types/descriptions. There is still magenta, gray and so on left.

How about one more: "Current release / magenta or gray? (description: obvious :smile: )"?

**Comment by antnieszka** [comment]
Or maybe let's just stick to milestone system...

**Comment by grzanka** [comment]
Speaking of milestones, see #66

**Comment by grzanka** [comment]
I agree with Major/Minor colors

**Comment by grzanka** [comment]
If you agree with milestone issue and have no other, please implement what was mentioned above.

**Comment by antnieszka** [comment]
Ok.

**Comment by antnieszka** [comment]
Current enhancement label will become type:future?

**Comment by grzanka** [comment]
enhancement = type:feature

**Comment by antnieszka** [comment]
If so - it's done.

**Comment by grzanka** [comment]
OK

**Comment by antnieszka** [comment]
@grzanka One more question - should we always use both type and priority label? Like: Feature+Minor, Bug+Major etc.?

**Comment by grzanka** [comment]
I would say if a priority is missing, then its medium. If Major is added, then it means it's urgent and has the highest priority. Minor label - the opposite.

**Comment by antnieszka** [comment]
Ok, makes sense to me.
