### ISSUE TITLE
Think of milestones naming

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#66]
A proposition of milestone naming:
- 0.1.0
- "Next release" or "Current release" (with some movable deadline)
- "Backlog" (without any deadline)

Let us assume that 0.1.0 was already released. 
We put most of the important and urgent tasks in "Next release" . We work on them until more-less deadline. In the meantime we tag few releases and push them to pypi server.
One milestone is achieved we change its name to the number of latest pip package version, say 0.1.3 and create new milestone called again "Next release". Then we do planning and move tasks from backlog to next release.

Why like this ?
Managing milestones is an addional burden and I was planning to release often (at least patches).
This way we could have broader milestones.

The disadvantage is that probably moving issues from backlog to milestone is time consuming.

**Comment by antnieszka** [comment]
I like the idea but... how about assuming backlog == not assigned to any milestone?

**Comment by grzanka** [comment]
I agree - backlog == not assigned is a good point.

Can you implement that ?

**Comment by antnieszka** [comment]
Ok, I will. What deadline should I set? End of next week? End of June?

**Comment by grzanka** [comment]
No preference - just do it when you have time.

**Comment by antnieszka** [comment]
Because we assume 0.1.0 was released, should I move all issues from milestone 0.1.0 to 'next release' or leave them be this one time?

**Comment by grzanka** [comment]
0.1.0 wasn't release yet:
https://github.com/DataMedSci/beprof/releases
I would then keep what is now marked '0.1.0' as it is.

When all issues in '0.1.0' I will myself create a 0.1.0 release - this should also trigger submission of package to pypi.

Other issues should go to 'next release'.

**Comment by grzanka** [comment]
You can also fix some issues planned for next release sooner (then you can simply change a category)

**Comment by antnieszka** [comment]
ACK. This one is done too.

**Comment by grzanka** [comment]
Can you set milestones also for closed issues and PRs ?

**Comment by antnieszka** [comment]
Assuming everything done is 0.1.0?

**Comment by antnieszka** [comment]
Or create pre-0.1.0 milestone?

**Comment by grzanka** [comment]
Everything in 0.1.0

**Comment by antnieszka** [comment]
Ok.
