### ISSUE TITLE
Think of faster build system

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#67]
It looks that with current configuration travis is pretty slow.
To merge a PR we need to wait >30 mins.

We should think on how to make commit + PR integration loop faster.

One idea would be to:
- have a more compact and fewer tests on travis
- run more tests elsewhere
  - on dedicated jenkins (we can have VM in PLGRID running it)
  - make a mirror of this repo on gitlab. Gitlab has very advanced embedded CI solution (gitlab runners). We can run have own, docker based runners in PLGRID. Currently gitlab can sync with github every 60 min, but with some tricks this can be faster.

In this way:
- short tests have passed and long ones are pending : admin decided whether to merge or not
- short tests have failed - we don't merge
- short and long tests passed - we probably merge

We can also add some bot and system of +1, -1 voting, like here: https://github.com/cms-sw/cmssw/pull/14889

**Comment by grzanka** [comment]
It would be also good to know why the running whole test machine is slow.

**Comment by antnieszka** [comment]
Have you investigated wercker?

**Comment by grzanka** [comment]
I've just added beprof to wercker (and made you admin). You can play around on https://github.com/DataMedSci/beprof/tree/feature/67-wercker-test

**Comment by antnieszka** [comment]
To avoid this travis thing I'm testing wercker on beprof fork: https://app.wercker.com/#applications/576a55b319a594010006c48e I've managed to create two-pipeline workflow with pytest.

**Comment by grzanka** [comment]
As you see builds are failing because wercker.yml is missing in MANIFEST file. Please add it to manifest.

**Comment by antnieszka** [comment]
Do we still need this? Or just improve wercker config (there is another issue for that, I think)
