### ISSUE TITLE
Better issue organization with overv.io 

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#72]
https://overv.io/DataMedSci/beprof/

Maybe we should consider using this, because in the long run we may become overwhelmed with controlling issues?

There are now 3 columns: new, in progress, closed. I think this requires some discussion - what kind of issue-flow will be best for this and future projects.

**Comment by grzanka** [comment]
Looks nice !

**Comment by antnieszka** [comment]
I just moved this issue to "In progress" on the overv board and look, label self-assigned on github too.

**Comment by grzanka** [comment]
Does overv.io support badges ?
Can you add a link to the README.md ?

**Comment by antnieszka** [comment]
As far as I can see - no badges :|
I'll add a link, maybe below badge table? Something like this:
[Overv.io issue board](https://overv.io/DataMedSci/beprof/)

**Comment by grzanka** [comment]
Looks OK. 

What about configuration of overv.io ?

**Comment by antnieszka** [comment]
Seems like labels made like `type:xxxx`, `status:yyyy` etc. are auto-grouped? Just look at single issue details (popup after clicking) or on this image:
![](http://i.imgur.com/4G4pqEd.png)

To make everything look nice on github and overv.io I would make some labels with `status:` prefix. My idea:
`status:open` (this one comes with overv.io)
`status:in progress`
`status:postponed`
`status:closed`

I also thought for a second about adding `status:discussion` but... any thoughts?

**Comment by grzanka** [comment]
It looks like that, but check overv.io documentation first - is it described there ?

**Comment by antnieszka** [comment]
It is: https://blog.overv.io/semantic-labels-and-improved-issues-4adfc8821c7c#.fms7ewoqg

**Comment by grzanka** [comment]
Speaking of status:XXX labels - do you mean modifing flow here ?
![screen shot 2016-06-21 at 00 22 51](https://cloud.githubusercontent.com/assets/7374733/16212191/645e16d0-3746-11e6-81bb-4d8a2e953347.png)

**Comment by antnieszka** [comment]
Yes, and blog note from my comment above. Looks like we can modify it. My proposition with `status` prefix comes from fact that all other labels have some prefix, only statuses don't.

**Comment by grzanka** [comment]
Proposition with status: is OK - I agree

**Comment by grzanka** [comment]
Just testing android app. Only 100 downloads
