### ISSUE TITLE
QuantifiedCode as automated Python code review

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#73]
https://www.quantifiedcode.com/

QuantifiedCode is an automated, data-driven code review for Python. They automatically analyze code and suggest changes. Maybe this would be better than pep builds?

**Comment by grzanka** [comment]
Adding a project in the organization is a bit cumbersome, but it seems to work:
https://www.quantifiedcode.com/app/project/d8c6bb41bcac4638a108c81994ba3846?tab=basics

I just don't get why naming a method "x" is a bad habit... This bastard wan't to have at least two characters as method name

**Comment by antnieszka** [comment]
Maybe there is a way to turn off this specific check...

**Comment by antnieszka** [comment]
~~I don't have admin rights but try searching in Settings -> Code checks~~

**Comment by antnieszka** [comment]
And we could add a new badge if we decide to use this [![Code Issues](https://www.quantifiedcode.com/api/v1/project/d8c6bb41bcac4638a108c81994ba3846/badge.svg)](https://www.quantifiedcode.com/app/project/d8c6bb41bcac4638a108c81994ba3846)

**Comment by antnieszka** [comment]
Ok, I did not see your invite - turning off this check: https://www.quantifiedcode.com/app/issue_class/be916a0f0d5a4d3dba403f9ff658a901

**Comment by antnieszka** [comment]
Done, the stupid 1-letter method check does not show anymore.

**Comment by antnieszka** [comment]
Ok, tool configured - closing this issue.
Let's discuss this 1-letter naming in separate issue: https://github.com/DataMedSci/beprof/issues/74
