### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#88]
On 19.08.2016 new version (3.0.0) of pytest pip package was issued, see https://pypi.python.org/pypi/pytest

It stopped to be compatible with python 3.2, which is causing Travis tests to fail, see:
https://travis-ci.org/DataMedSci/beprof/builds/153925435

One of solutions to that problem is to use conditional requirements, see i.e.:
https://github.com/DataMedSci/pymchelper/blob/master/tests/requirements-test.txt

**Comment by grzanka** [comment]
@ant6 can you take a look ?

**Comment by antnieszka** [comment]
@grzanka I think Python 3.2 is getting pretty old (February 20th, 2011) and even more libraries may drop support for it - and that's why we probably should use conditional requirements. Soon this may happen to other versions too :/

**Comment by grzanka** [comment]
If I remember correctly Python 3.2 is default on Ubuntu 12.04. Check how long it will be supported

**Comment by antnieszka** [comment]
According to https://wiki.ubuntu.com/LTS end of 2017

**Comment by grzanka** [comment]
So until that time we need to live with Python 3.2

**Comment by grzanka** [comment]
@ant6 Can you fix it ?

**Comment by antnieszka** [comment]
@grzanka Yes :)

**Comment by antnieszka** [comment]
Closed in #89
