### ISSUE TITLE
Requires.io shows outdated

### ISSUE THREAD

**Issue by antnieszka** [DataMedSci/beprof#90]
https://requires.io/github/DataMedSci/beprof/requirements/?branch=master
Probably because of the conditional requirement for pytest.

**Comment by grzanka** [comment]
Not a bug. pytest<3.0 is intentional.

**Comment by antnieszka** [comment]
@grzanka I know it is, but now we have "outdated" badge status on https://github.com/DataMedSci/beprof :|

**Comment by grzanka** [comment]
Can you do something with that (change the status of requires.io and keep existing reqs) by using directives, as described here: https://requires.io/features/#rq-directives ?

**Comment by antnieszka** [comment]
@grzanka fixed in #91
